Support GCC 5.1.

diff --git a/util/find-cxx b/util/find-cxx
--- a/util/find-cxx
+++ b/util/find-cxx
@@ -1,8 +1,12 @@
 #!/bin/sh
 
-for a in "g++-4.9" "g++-4.8" "g++"; do
+for a in "g++-5.1" "g++-5" "g++-4.9" "g++-4.8" "g++"; do
     if "$a" "-dumpversion" > /dev/null 2>&1; then
         case "$($a -dumpversion)" in
+        5.*)
+            echo "$a"
+            exit 0
+            ;;
         4.[89].*)
             echo "$a"
             exit 0
@@ -14,5 +18,5 @@ for a in "g++-4.9" "g++-4.8" "g++"; do
         esac
     fi
 done
-echo "could not find a suitable C++ complier" >&2
+echo "could not find a suitable C++ compiler" >&2
 exit 1
